### ISSUE TITLE
getAllInFolder() Not returning all Files.

### ISSUE THREAD

**Issue by nathang21** [tanaikech/FilesApp#1]
This Library seems fantastic and exactly what I need for some simple Google Drive Automation. However, I am trying to use the `getAllInFolder()` function but it's only returning a subset of files out of the expected 23 files. Not sure if this is relevant but the folderID I am searching, is within a Shared Drive. 

`FilesApp.getAllInFolder('folderId', null, "files(id,mimeType)");`

3 of these are nested folders, (only 1 level deep) and within those folders there are combined 20 images, and 1 PDF.

The response i'm getting is only containing 7 files but it seems random what is returned. 
- All 3 folders
- 1 PDF
- 3 Random photos (not all) from 1 of the sub folders.

I can't figure out why it's ignoring all the other photos.

I'm happy to provide for more details if you let me know how best to debug.

**Comment by nathang21** [comment]
For to add, not sure if this is relevant but the folderID I am searching, is within a Shared Drive.

**Comment by tanaikech** [comment]
Thank you for your comment. I could confirm the same situation. The reason was the incomplete parameters for requesting to Drive API. I modified this and I could confirm that the issue was removed. And this library was updated to v1.1.2. Please confirm it.

**Comment by nathang21** [comment]
Looks like that did the trick, thanks for the quick fix!
